
**Content:**

```yml
blank_issues_enabled: false
contact_links:
  - name: ðŸ“˜ Shift6 Formatter Marketplace Page
    url: https://marketplace.visualstudio.com/items?itemName=lakdogan.shift6foribmi
    about: Documentation, features, and release information
